name: Auto Clean Playlist
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  clean_m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Run Cleaner Script
        run: python playlist_cleaner.py
        
      - name: Save Cleaned Playlist
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # This line tells the Robot to grab the file even if it's new
          git add -A 
          git commit -m "Update Stealth Playlist" || echo "No changes to commit"
          git push
